### ISSUE TITLE
Please fix your code example

### ISSUE THREAD

**Issue by ltworf** [mosquito/cysystemd#11]
```
from systemd.daemon import notify, Notification
```

That doesn't work: `ImportError: cannot import name 'Notification'`

I'm calling it as `notify('READY=1')`, but please do put examples that work.

**Comment by mosquito** [comment]
Please provide some information about your environment (e.g. Python version, Linux distribution, etc.)

**Comment by ltworf** [comment]
Ok so this seems to be the issue.

On pypi there are:
 * systemd
 * python-systemd
 * systemd-python

Out of those, `systemd-python` is the official one, and is installed on ubuntu as `python3-systemd` (which generated my confusion). So I was trying to use a different module.

Can you please add something in your README about this entire situation? Like your module not being the official one, and not being shipped in debian/ubuntu, despite the similar names.

**Comment by mosquito** [comment]
Fixen on #4
