### ISSUE TITLE
Prevent logging to syslog?

### ISSUE THREAD

**Issue by p-doyle** [mosquito/cysystemd#16]
Sorry this isn't really an issue but wasn't sure where else to ask... I am wondering if there is a way to send messages to systemd without having them written to syslog as well?  I see there is the 'facility' var in the JournaldLogHandler that seems like it would allow me to write to the auth log or something else but I'd prefer not to log to any of them.  Is that possible?

Thanks!

**Comment by mosquito** [comment]
See [ForwardToSyslod=](https://www.freedesktop.org/software/systemd/man/journald.conf.html) option.

**Comment by p-doyle** [comment]
Looks promising... Thanks!  Do you know if is this something that can be set or controlled for just cysystemd?  I am fine with having other system services write to syslog, just didn't want my python scripts to.

**Comment by mosquito** [comment]
cysystemd it’s just wrapper for libsystemd. Unfortunately libsystemd not provide this directly. You could ignore this logs for rsyslog or disable forwarding. The forwarding duplicates log records. Records will be stores in journald and syslog file twice but syslog records will contains only message other fields will be dropped. That’s default made for compatibility and IMHO useless for modern systems.

**Comment by p-doyle** [comment]
Got it, thanks!  Will close...
