### ISSUE TITLE
Rules are clunky

### ISSUE THREAD

**Issue by cmm** [mosquito/cysystemd#21]
The set of filter expressions you can build using the Rule class and its & and | operations is a strict subset of what sd_journal_add_{match,disjunction,conjunction}() provide.  IMHO it would be better (and also simpler) to just expose those, the way the official SystemD binding does it.

**Comment by mosquito** [comment]
Sorry for the long reply, notification lost in the mail.

In short, I haven't paid much attention to this functionality, but can you offer me how you see it, in the form of example code or PR may be.

**Comment by cmm** [comment]
Heh.  This was a long time and two jobs ago, and I cannot remember any context now, sorry!

**Comment by mosquito** [comment]
Never mind, fell free to reopen it.
