### ISSUE TITLE
JournalEntry timestamps are incorrect

### ISSUE THREAD

**Issue by mike-twa** [mosquito/cysystemd#27]
Thanks for the work on this, it has been super useful!

It seems that the values of `.get_realtime_sec()` is getting returned as a float, when it needs to be a double.  As a result the `.date` value is incorrect as well.

Here is some sample output where I would expect `get_realtime_sec()` to return `1599083674.346608`, but instead:
```
>>> cysystemd.__version__
'1.3.3'
...
>>> journal_entry.get_realtime_usec()
1599083674346608
>>> journal_entry.get_realtime_sec()
1599083648.0
>>> journal_entry.date
datetime.datetime(2020, 9, 2, 21, 54, 8)
```
I'm not familiar with cython but I'm hoping all that needs to happen is changing the return types for `get_realtime_sec()` and `get_monotonic_sec()` to `double`?

**Comment by mosquito** [comment]
It's [computed properties](https://github.com/mosquito/cysystemd/blob/master/cysystemd/reader.pyx#L262-L263).

**Comment by mike-twa** [comment]
I'm not sure I understand, is it that I'm using the methods incorrectly?

It seems like `get_realtime_usec()` returns a `uint64_t` with value `1599083674346608`.
Then `get_realtime_sec()` takes that value, divides it by `1000000` and returns that.  However since the return type is `float` the result loses precision as the 32-bit floating point representation `1599083648.0` of what should be a 64-bit `double` value `1599083674.346608`
