### ISSUE TITLE
Python 2 compatibility is broken

### ISSUE THREAD

**Issue by aj-anet** [mosquito/cysystemd#34]
The function definition of notify in daemon.py is python 3 format.

https://github.com/mosquito/cysystemd/blob/d9c9a8e7044331cb668b109b36ee82b7117cfda4/cysystemd/daemon.py#L31

Introduced in https://github.com/mosquito/cysystemd/commit/91bf53235b5499da4899570d4968e2674d461e01

**Comment by mosquito** [comment]
python2 is not supported
