### ISSUE TITLE
pip install error 

### ISSUE THREAD

**Issue by L0ric0** [mosquito/cysystemd#36]
the a gcc command exits with error code 1 while trying to install with python3.9 and gcc10. the error log is attached

[log.txt](https://github.com/mosquito/cysystemd/files/5754118/log.txt)

**Comment by mosquito** [comment]
Could you please provide the any way to reproduce it? Maybe docker image or something else?

**Comment by ddibiasi** [comment]
Happens to me as well. I'm running:

- gcc 10.2.0-4
- python 3.9.1-1
- kernel 5.9.14-arch1-1

Console output is attached.
[output.txt](https://github.com/mosquito/cysystemd/files/5775753/output.txt)

**Comment by mosquito** [comment]
wheels added to pypi
