### ISSUE TITLE
name conflicts with systemd's own python bindings; how to package?

### ISSUE THREAD

**Issue by tkluck** [mosquito/cysystemd#4]
Thanks for these excellent bindings; they are certainly much more pythonic than the ones that systemd ships.

I'm trying to package this library as I have my own software depending on it. This is quite hard, because at least in debian, `import systemd` is already taken by the official bindings.

In general, the naming conventions have become a bit unfortunate:

place |  official systemd    |         mosquito
------ | ----------- | --------------------------
github |   `python-systemd`  |     `python-systemd`
pypi    |  `systemd-python`   |    `systemd`
debian |    `python{,3}-systemd` | ?
`import` statement | `import systemd` | `import systemd`

What's your preferred way of handling this? A possible suggestion would be to rename to `pysystemd`, but I'm just thinking out loud here.

**Comment by mosquito** [comment]
You are absolutelly right, actually I don't know what can I do with this collisions. Some my projects already require it as systemd.

My own solution: Making RPM package which contains a virtualenv with all dependencies.

And the second one solution: You could build package with different name (e.g. cython-systemd) and add `Conflicts` section for this (which contains python{,3}-systemd).

I hope this options would helps you.

**Comment by tkluck** [comment]
Thanks for your thoughts @mosquito ! Hmmm, if you already depend on it for many projects, a rename is not really going to work. That does mean that it can't be officially packaged for debian/ubuntu , because they probably wouldn't accept a virtualenv-based solution. Is that an issue for you?

For my own project, I'm going to go with this solution here: https://github.com/tkluck/pac4cli/pull/9/commits/dc5d7a8865d072dbf6c168a40db004530882a2b2 . It's a bit silly, but it does allow both a `pip` (yours) and a debian (official systemd) based installation.

**Comment by kiltum** [comment]
Actually it now broke ansbile ;)

https://github.com/ansible/ansible/issues/33523

**Comment by mosquito** [comment]
This is an issue for "ansible" team. Distutils has internal requirements validation. `systemd` and `python-systemd` is a different packages.

**Comment by kiltum** [comment]
Yes, so i filed bug. But i know that you use ansible, so be warned ;)

**Comment by mosquito** [comment]
Package has been renamed as `cysystemd`
