### ISSUE TITLE
PyPI doesn't provide the arm64 wheels

### ISSUE THREAD

**Issue by multani** [mosquito/cysystemd#45]
In #39, the project now builds wheels for arm64 (aarch64) platform, which is great :tada: 

However, PyPI only contains the [amd64 (x86_64) variants](https://pypi.org/project/cysystemd/#files): would it be possible to also provide all the wheels from the latest releases directly through PyPI?

I had a look both at the Travis and GitHub Actions workflow, but I couldn't find if the upload to PyPI was automated or not.

Let me know if I can help!

**Comment by mosquito** [comment]
When you try to upload it to the pypi you catch the error cause the pypi doesn't support it.

**Comment by multani** [comment]
> When you try to upload it to the pypi you catch the error cause the pypi doesn't support it.

Oh :(

Could you share the command you are using to upload to PyPI and the error message you have (if you still have it)?

There are some packages which ([MarkupSafe](https://pypi.org/project/MarkupSafe/#files), [PyYAML](https://pypi.org/project/PyYAML/#files) to name those I know) which provide these wheels, I'd be happy to help and give it a try on my personal PyPI :+1:

**Comment by mosquito** [comment]
```$ twine upload --skip-existing cysystemd-1.4.8-cp39-cp39-linux_aarch64.whl                                                                                                                                                       16:20:31 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading cysystemd-1.4.8-cp39-cp39-linux_aarch64.whl
100%|██████████████████████████████████| 1.85M/1.85M [00:02<00:00, 752kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Binary wheel 'cysystemd-1.4.8-cp39-cp39-linux_aarch64.whl' has an unsupported platform tag 'linux_aarch64'.
```
