### ISSUE TITLE
Automatic wheels publishing to PyPi

### ISSUE THREAD

**Issue by BoboTiG** [mosquito/cysystemd#62]
I saw you store wheels on GitHub releases pages, and only the source is uploaded to PyPi.

Would you be interested in a GitHub workflow to do the whole work of compiling + publishing everything to PyPi? It would ease the life of all users :)

**Comment by mosquito** [comment]
IMHO It's have no prcatical impact, because the target shared library will be linking with libsystemd and the libsystemd api changes will break the wheel.
